  DatabaseSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    DependsOn:
      - PrivateSubnet2
      - PrivateSubnet1
    Properties:
      DBSubnetGroupDescription: The subnet group for RDS Aurora
      SubnetIds:
        - Ref: PrivateSubnet1
        - Ref: PrivateSubnet2
  DatabaseCluster:
    Type: AWS::RDS::DBCluster
    DependsOn:
      - PrivateSubnet1
      - PrivateSubnet2
      - DatabaseSecurityGroup
      - DatabaseSubnetGroup
      - NATGateway1
      - NATGateway2
    Properties:
        Engine: 'aurora-mysql'
        EngineVersion: '5.7.12'
        MasterUsername:
            Ref: DatabaseUsername
        MasterUserPassword:
            Ref: DatabasePassword
        BackupRetentionPeriod:
            Ref: DatabaseBackupRetentionPeriod
        PreferredBackupWindow: 02:00-04:00
        PreferredMaintenanceWindow: mon:04:00-mon:05:00
        DBSubnetGroupName:
            Ref: DatabaseSubnetGroup
        DBClusterParameterGroupName: 'default.aurora-mysql5.7'
        DatabaseName:
          Ref: MyDatabaseName
        VpcSecurityGroupIds:
          -  Ref: DatabaseSecurityGroup
        StorageEncrypted: 'true'
  DatabasePrimaryInstance:
    Type: AWS::RDS::DBInstance
    DependsOn: DatabaseCluster
    Properties:
        Engine: 'aurora-mysql'
        DBClusterIdentifier:
            Ref: DatabaseCluster
        DBInstanceClass:
            Ref: DatabaseInstanceType
        DBSubnetGroupName:
            Ref: DatabaseSubnetGroup
        DBParameterGroupName: 'default.aurora-mysql5.7'
  DatabaseReplicaInstance:
    Type: AWS::RDS::DBInstance
    DependsOn:
      - DatabaseCluster
      - DatabasePrimaryInstance
    Properties:
        Engine: 'aurora-mysql'
        DBClusterIdentifier:
            Ref: DatabaseCluster
        DBInstanceClass:
            Ref: DatabaseInstanceType
        DBSubnetGroupName:
            Ref: DatabaseSubnetGroup
        DBParameterGroupName: 'default.aurora-mysql5.7'
